server:
  port: 8762

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/
spring:
  application:
    name: @pom.artifactId@
  devtools:
    restart:
      endbled: true

feign:
  hystrix:
    enabled: true
