#server:
#  port: 8080
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: gateway-service #我们自定义的路由 ID，保持唯一
#          uri: https://blog.csdn.net #目标服务地址
#          order: 0
#          predicates:
#  #          - Path=/meteor_93 #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
#  #          - Between=2019-01-01T00:00:00+08:00[Asia/Shanghai], 2021-07-01T00:00:00+08:00[Asia/Shanghai]
#  #          - Before=2019-01-01T00:00:00+08:00[Asia/Shanghai]
#  #          - After=2019-01-01T00:00:00+08:00[Asia/Shanghai]
#  #          - Cookie=sessionId, test
#  #          - Host=**.baidu.com
#  #          - Header=X-Request-Id, \d+
#            - Method=GET

server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug